name: Upload branch to Upload Server
on: [push]
jobs:
  deploy_job:
    runs-on: ubuntu-latest
    name: deploy
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: getting branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: branch_name
      - name: zipping files
        run: zip -r ${{ github.event.repository.name }}_${{ steps.branch_name.outputs.branch }}.zip . -x '*.git*'
      - name: uploading archive
        uses: wlixcc/SFTP-Deploy-Action@v1.0
        with:
          username: 'boomi'
          server: 'upload.zoominsoftware.io'
          ssh_private_key: 'eae95559ef4f4284d8f3cdb5f545de3863292188340ff8ed4b98fff15b062cd0'
          local_path: ${{ github.event.repository.name }}_${{ steps.branch_name.outputs.branch }}.zip
          remote_path: 'boomi-be-staging.zoominsoftware.io/dita-vasont/incoming'
          # remote_path: 'storm-be-dev.zoominsoftware.io/${{ steps.branch_name.outputs.branch }}/incoming/'
          args: '-o ConnectTimeout=5'
